apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    component: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                component: webapp
      containers:
      - image: haongo/webapp
        imagePullPolicy: Always
        name: webapp
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 128Mi
            cpu: 400m
          requests:
            memory: 64Mi
            cpu: 200m
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5