---
- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent

- name: Ensure dependencies are installed.
  yum:
    name:
      - yum-utils
      - python3-pip
    state: present

- name: Add Docker repository
  shell: yum-config-manager --add-repo={{ docker_yum_repository }}
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
